### ISSUE TITLE
Issue parsing const type typehints

### ISSUE THREAD

**Issue by ClaudiuC** [fredemmott/definition-finder#15]
[This exception](https://github.com/fredemmott/definition-finder/blob/16af9cc08a037792b0e736d847c48ef1e1e502c4/src/consumers/FunctionAbstractConsumer.php#L163) comes up in some cases if you have a typehint like this::Foo, ie:

```
class Foo {
  const type Bar = int;
  
  public function getBar(
    this::Bar $bar,
   ): Bar {}
}
```

However, it's not consistent so I'm trying to pin it down to a clean repro. In the same file I run into [this exception](https://github.com/fredemmott/definition-finder/blob/db3839826b5414636b4c432fa03df16d596c4ab7/src/consumers/ScopeConsumer.php#L93) too, but apart from const typehints, I'm not really doing anything out of the ordinary that I don't in other files. The syntax should be correct, works at runtime and I don't get any Hack errors.

**Comment by ClaudiuC** [comment]
Ok, I think I found the problem - I didn't look at the parser code yet though. The problem seems to be with parsing `abstract const type <name> [as <constraint>];`

With a minimal example:
```
abstract class Foo {
   abstract const type Foos as arraykey;
}
```

I'll get an invalid constant definition. I assume that in my larger class where I do this, the other exceptions I'm seeing are just due to the parser losing track.

**Comment by ClaudiuC** [comment]
My local dirty fix for this was:

- Add a condition (here)[https://github.com/fredemmott/definition-finder/blob/db3839826b5414636b4c432fa03df16d596c4ab7/src/consumers/ConstantConsumer.php#L36] to check for `as` as well as `=`

- In `FunctionAbstractConsumer` check for `T_DOUBLE_COLON` and shift the token queue if found since it's likely a type parameter. 

This makes the map autoloader to work, if I get some time to properly fix this I'll PR.

**Comment by kilahm** [comment]
@ClaudiuC I would love some feedback on my solution to this, see the attached PR #24

**Comment by fredemmott** [comment]
https://github.com/fredemmott/definition-finder/commit/b980f1369d58ee083c2fbdc5d9fc08316056a4b2 fixes the blockers @kilahm  raised
