### ISSUE TITLE
User attribute arrays don't parse

### ISSUE THREAD

**Issue by HRMsimon** [fredemmott/definition-finder#37]
```hack
<?hh

require 'vendor/autoload.php';

try {
  $parser = FredEmmott\DefinitionFinder\FileParser::fromData(
    <<<'FILE'
<?hh

<<Foo([1])>>
class Baz {}
FILE
  );
} catch (Exception $e) {
  var_dump($e->getPrevious()->getMessage());
}
```

```
# hhvm test.php 
string(47) "Invalid attribute value token type at line 3: 0"
```

It's not handling the `[`. Is valid Hack though.

**Comment by fredemmott** [comment]
https://github.com/facebook/hhvm/blob/68c607a8edeba17e2ac0bd672d279615b68bff5b/hphp/parser/hphp.y#L2727-L2753

sadpanda.

**Comment by fredemmott** [comment]
@sgolemon: some of these might be useful to you; TL;DR: have a user-space evaluator for static_scalar_ae from tokens.

**Comment by fredemmott** [comment]
@HRMsimon : I'm holding off on doing a new release until I've got time to test master in the HHV docs build process
