### ISSUE TITLE
Use new user-attribute evaluation code to evaluate constants

### ISSUE THREAD

**Issue by fredemmott** [fredemmott/definition-finder#41]
Going to release it separately as this is a higher-risk change

**Comment by fredemmott** [comment]
Not sure if this will be practical - eg this is allowed generally, but not in user attributes:

```PHP
class foo {
    // As of PHP 5.6.0
    const TWO = ONE * 2;
    const THREE = ONE + self::TWO;
    const SENTENCE = 'The value of THREE is '.self::THREE;
}
```

**Comment by fredemmott** [comment]
One option would be to return an object that can both return the source text (current behavior), /or/ evaluate it - the latter would fail if any user-defined-constants are referenced.

@doublecompile , @HRMsimon  - thoughts?

**Comment by HRMsimon** [comment]
Would be nice if user attributes supported all the same things as class constants.

Having a way to get the result of any static expression would be useful, as would being able to get an AST (or similar) out.

**Comment by fredemmott** [comment]
Closing for now, this isn't really practical until we get a full AST, which is much more involved. Hopefully Phack will get more complete parser support, then I can borrow Phack's extensions to nikic's parser to do it.
