### ISSUE TITLE
ParseException for aws-sdk-php

### ISSUE THREAD

**Issue by eryi** [fredemmott/definition-finder#45]
# How to reproduce
From: https://github.com/fredemmott/hhvm-autoload/issues/10

    require aws/aws-sdk-php:3.20.10

# Error thrown
````
[FredEmmott\DefinitionFinder\ParseException]                                 
  /home/nonroot/app/src/vendor/aws/aws-sdk-php/src/Api/DocModel.php:106: Don'  
  t understand public/private/protected outside of a class at line 106 
````

# Link to file
https://github.com/aws/aws-sdk-php/blob/master/src/Api/DocModel.php#L106

**Comment by jesseschalken** [comment]
As a guess, it's probably confused by the `T_DOLLAR_OPEN_CURLY_BRACES` in `"...${ref}"` on [line 93/94](https://github.com/aws/aws-sdk-php/blob/master/src/Api/DocModel.php#L93) which it should probably treat the same as a `T_CURLY_OPEN` and `{`, [but doesn't appear to](https://github.com/fredemmott/definition-finder/search?utf8=%E2%9C%93&q=T_CURLY_OPEN), causing the next `}` to be mismatched against the last `{` and so on.
