### ISSUE TITLE
Support installation (but not execution) on Zend

### ISSUE THREAD

**Issue by jesseschalken** [fredemmott/definition-finder#49]
I'm writing Hack that runs on both HHVM and Zend via `h2tp`, and I want to use [appertly/hphpdoc](https://github.com/appertly/hphpdoc) to generate docs, which in turn uses definition-finder.

With definition-finder installed via Composer, including `vendor/autoload.php` on Zend causes the `src/typedefs.php` and `src/utils.php` files to be output, since they are included unconditionally and Zend doesn't recognise the `<?hh` opening tag.

To solve this use case, how about putting a file like this in the root instead, and including that from `composer.json=>autoload=>files`?

```php
<?php

if (\defined('HHVM_VERSION')) {
  require_once __DIR__.'src/utils.php';
  require_once __DIR__.'src/typedefs.php';
}
```

**Comment by fredemmott** [comment]
Can you also solve this by having it as a dev dependency, not a runtime dependency?

**Comment by jesseschalken** [comment]
Yes, but I also need dev-dependencies to be installed to run tests and to generate the [`include.php`](https://github.com/jesseschalken/hack-utils/blob/master/hack/include.php), and the `src/typedefs.php` and `src/utils.php` files get output when I do both of those things on Zend.

**Comment by jesseschalken** [comment]
Thanks for fixing this @fredemmott
