### ISSUE TITLE
Issue with undefined function `nullthrows`

### ISSUE THREAD

**Issue by mhahn** [fredemmott/definition-finder#52]
Moved over from: https://github.com/fredemmott/hack-router-codegen/issues/14

HHVM Version:

```
HipHop VM 3.17.1 (rel)
Compiler: tags/HHVM-3.17.1-0-gdb3429c2130e5f7539bfd550c27a6bea9444b669
Repo schema: 68c9b831b56bea5d8c90f6fca5ea358cdaaea626
```

composer.json: https://github.com/mhahn/hhvm-sample/blob/master/composer.json

I'm trying to get a simple example of this running but I'm getting this error when I try and run it:
```
Fatal error: Call to undefined function FredEmmott\DefinitionFinder\nullthrows() in /var/www/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php on line 637
```

I'm trying to run:

```
<?hh

require_once(__DIR__.'/../vendor/hh_autoload.php');

use \FredEmmott\HackRouter\Codegen;

Codegen::forTree(
	__DIR__.'/../src/',
	shape(
		'controllerBase' 	=> \Controller::class,
		'router' 			=> shape(
			'abstract' 	=> false,
			'file' 		=> __DIR__.'/../src/Router.hh',
			'class' 	=> 'Router',
			'namespace' => 'Sample',
		)
	),
)->build();
```

I pushed up my sample code if it helps: https://github.com/mhahn/hhvm-sample.

**Comment by fredemmott** [comment]
Only with hhvm-autoload, and due to https://github.com/fredemmott/definition-finder/commit/d86368f6b3a6c6a0df3ee5b9bea33f6abc78308c

**Comment by fredemmott** [comment]
Also needs a change to hhvm-autoload to fix this.
